artifact_location: file:///Users/bhavasan/learning/ML-Projects/employee_attrition_prediction/mlruns_validation/0/models/m-dcef1a196c804a54a6febac168e0a4d9/artifacts
creation_timestamp: 1782213347241
experiment_id: '0'
last_updated_timestamp: 1782213355297
model_id: m-dcef1a196c804a54a6febac168e0a4d9
model_type: null
name: model
source_run_id: 84730341409646c5bf3d2500fd86de87
status: 2
status_message: null
