artifact_uri: file:///Users/bhavasan/learning/ML-Projects/employee_attrition_prediction/mlruns_validation/0/84730341409646c5bf3d2500fd86de87/artifacts
end_time: 1782213355649
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 84730341409646c5bf3d2500fd86de87
run_name: Gradient Boosting Classifier validation
source_name: ''
source_type: 4
source_version: ''
start_time: 1782213329300
status: 3
tags: []
user_id: bhavasan
